language: common-lisp

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=ecl

install:
  # Qt
  - sudo apt-get update -qq
  - sudo apt-get install -y libqt4-dev qt4-qmake libphonon4 libphonon-dev libqt4-opengl libqt4-webkit
  # X server
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # CL
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -e '(ql:quickload :qt-lib-generator)'
       -e '(setf qt-lib-generator::*max-cpus* 4)'
       -e '(ql:quickload :qt-libs)'
       -e '(qt:make-qapplication)'
       -e '(format T "~&~%!!! WOAH IT WORKS !!!~&~%")'

notifications:
  email:
    - shinmera@tymoon.eu